export interface MutualFunds {
    id?: number,
    ticker?: string,
    name?: string,
    assetClass?: string,
    risk?: string,
    expenseRatio?: number,
    secYield?: number,
    ytd?: number,
    oneYr?: number,
    threeYr?: number,
    fiveYr?: number,
    tenYr?: number,
    sinceInception?: number,
    initialInvestment?: number,
    price?: number,
    changePrice?: number,
    changePricePercent?: number,
    inceptionDate?: string,
    shortName?: string,
    subsequentInvestment?: number,
    fundFamily?: string,
    totalNetAssets?: number,
    investmentType?: string,
    sizeType?: string,
    investmentStrategy?: string
}